Fork devcert
adobe/ccweb-add-on-devcert pull request #1
Opened 2023-09-30 22:40 UTC by xerxovksi

## Description

Fork [devcert](https://github.com/davewasmer/devcert.git)

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-02 22:31 UTC, kerrishotts requested changes

2023-10-02 22:31 UTC, kerrishotts commented on LICENSE
We can't take over the copyright here; so while a portion of our changes are (C) Adobe, the original copyright holder needs to be listed here too.

So I'd do something like this:

```
(C) Copyright Dave Wasmer
Portions (C) Copyright 2023 Adobe.
```

2023-10-02 22:31 UTC, kerrishotts commented on README copy.md
In our fork notice, let's include the orignal author's name & copoyright


(i) Note

This is a fork of devcert (Copyright Dave Wasmer). (etc.)

2023-10-03 13:55 UTC, xerxovksi commented on LICENSE
Updated.

2023-10-03 13:56 UTC, xerxovksi commented on README copy.md
Added.

2023-10-03 14:15 UTC, kerrishotts approved these changes
LGTM

2023-10-03 14:16 UTC, merged